spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri:
            lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - AuthenticationFilter

        - id: transaction-service
          uri:
            lb://transaction-service
          predicates:
            - Path=/transactions/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri:
            lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri:
            lb://identity-service
          predicates:
            - Path=/auth/**


server:
  port: 6969

eureka:
  instance:
    hostname: localhost

  client:
    fetch-registry: true
    register-with-eureka: true